# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 3006

# ==============================================================================
# K A F K A
# ==============================================================================
kafka:
  host: localhost
  groupId: gentlecorp-notification-service

# ==============================================================================
# K e y c l o a k
# ==============================================================================
keycloak:
  authServerUrl: http://localhost:8880
  realm: vibeCheck
  clientId: vibeCheck
  
# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  #dir: ./log
  pretty: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  #activated: false
  host: localhost
  port: 5025
  log: false