# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 7402

# ==============================================================================
# K A F K A
# ==============================================================================
kafka:
  host: localhost
  groupId: gentlecorp-notification-service
  
# ==============================================================================
# K e y c l o a k
# ==============================================================================
# "Client Secret" muss durch die Umgebungsvariable CLIENT_SECRET gesetzt werden
keycloak:
  #schema: http
  host: localhost
  port: 18080
  realm: camunda-platform
  # siehe Keycloak Menuepunkt "Clients" > Tab "Clients list" > Spalte "Client ID"
  clientId: camunda-identity
  #tokenValidation: online

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  #dir: ./log
  pretty: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  #activated: false
  host: localhost
  port: 5025
  log: false